apiVersion: v1
kind: PersistentVolume
metadata:
  name: nagios-pv
  namespace: nagios
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nagios
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nagios-pvc
  namespace: nagios
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
